### ISSUE TITLE
Break long words

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-frontend#11]
If there are words wider than the view, the layout breaks. 

![82E5FD65-FAF3-49BC-A9B5-876D65929184](https://user-images.githubusercontent.com/29376715/65839803-13f0ad00-e311-11e9-9a0b-47d1360c4bd2.jpeg)

**Comment by gruselhaus** [comment]
Erledigt.

**Comment by jnnkB** [comment]
Unten bei den Erklärungen wenn es falsch ist, gibt es den Fehler immer noch

![JEIhJAVfTY+6SRg29sylyw_thumb_4bcf](https://user-images.githubusercontent.com/29376715/65918383-d2780480-e3d9-11e9-895e-10fa9f2427da.jpg)

**Comment by gruselhaus** [comment]
Ups, ich habe das CSS Property nur fürs Statement gesetzt. Wird behoben.
