### ISSUE TITLE
Preload the next items

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-frontend#14]
Currently the next item is fetched when needed. I think we should preload the next 10 Items.

**Comment by redsolver** [comment]
#20

**Comment by gruselhaus** [comment]
@redsolver jetzt tritt ein komischer Bug auf. 
<img width="1792" alt="Bildschirmfoto 2019-09-30 um 18 58 31" src="https://user-images.githubusercontent.com/33380107/65899578-50291980-e3b4-11e9-8a07-3915c8c2e24b.png">

Bitte mal schnell nachgucken und fixen

**Comment by gruselhaus** [comment]
@redsolver Fix bitte ins #22 packen

**Comment by redsolver** [comment]
Behoben

**Comment by gruselhaus** [comment]
Top 👍🏻 Danke!
