### ISSUE TITLE
Link zum Spiel mit bestimmter These

### ISSUE THREAD

**Issue by kmille** [Jugendhackt/parteiduell-frontend#18]
Ich bin gerade auf folgende These gestoßen und hätte sie gerne mit jemanden geteilt:
"In Deutschland soll es ein bedingungsloses Grundeinkommen geben."

Ich fände es cool, wenn man eine URL zu parteiduell.de bekommen kann, mit der ein anderer das Spiel mit genau dieser These spielen kann.

**Comment by jnnkB** [comment]
We'll need the issue https://github.com/Jugendhackt/parteiduell-backend/issues/27 closed first. Then we could use the fragment identifier or a GET argument to specify which statement it shown.

**Comment by redsolver** [comment]
Der Link zur These sollte auch die zur Auswahl stehenden Parteien enthalten, damit auch die selbe Auswahl angezeigt wird.

**Comment by jnnkB** [comment]
Ja stimmt

**Comment by redsolver** [comment]
Einzelne Thesen sind jetzt abrufbar: https://github.com/Jugendhackt/parteiduell-backend/commit/edad95580597229ff36982372c4725c5ce04b1fa

**Comment by jnnkB** [comment]
Perfekt. Habe aktuell leider etwas Stress. Schaffe das nicht so bald. Wäre aber sehr cool.

**Comment by jnnkB** [comment]
Ich bin gerade dabei dieses Feature einzubauen. Es ist eigentlich zu großen Teilen relativ einfach. Ich habe es jetzt soweit, dass immer die richtige These angezeigt wird und die zur Auswahl stehenden Parteien die gleichen bleiben. Allerdings sollte sich ja auch nicht verändern welches Statement einer Partei angezeigt wird. Wenn ich das aber einfach direkt in der URL speichere kann man ja ganz einfach die Lösung auslesen. Hat jmd. eine Intelligente Lösungsidee? @lmaertens @gruselhaus @redsolver

**Comment by jnnkB** [comment]
Aktuell gebe ich halt id und Parteien so an:
https://api.parteiduell.de/list?id=WOM-42-7&parties=NPD,GR%C3%9CNE,CDU/CSU,SPD

**Comment by jnnkB** [comment]
Ich habe jetzt einfach mal base64 probiert gehabt, aber da lernt man leider viel zu schnell was es ist.

**Comment by kmille** [comment]
Vorschlag: macht doch neben /list noch einen anderen API-Endpunkt. z. B. /these
Da gibt man als Parameter die These-ID (WOM-42-7) mit und man bekommt die Lösung sowie die Parteien samt Logos zurück.

**Comment by jnnkB** [comment]
Du meinst, dass man immer frontend einfach eine Ansicht zur Betrachtung eine These bekommt? Oder für was soll url /these sein? Weil ich ja dann immer noch nicht weiß, von welcher Partei die These angezeigt werden soll.

**Comment by jnnkB** [comment]
Ich glaube ich hashe einfach das Statement der Partei

**Comment by kmille** [comment]
> Du meinst, dass man immer frontend einfach eine Ansicht zur Betrachtung eine These bekommt? Oder für was soll url /these sein? Weil ich ja dann immer noch nicht weiß, von welcher Partei die These angezeigt werden soll.

z. B. Ich schicke jemanden den Link parteiduell.de?these=WOM-42-7
Dann wird im Hintergrund eine Request an das Backend geschickt:
/api/these?these=WOM-42-7 und als Antwort kommt dann alles was du braucht (was er anzeigen soll, die Lösung, die Aussagen der Parteien, etc. )

**Comment by jnnkB** [comment]
Das Problem ist halt, dass dann der Browser nicht weiß welche Parteien er zur Auswahl stellen soll und welches Statement einer Partei zur These angezeigt werden soll. Die ID bezieht sich nämlich nur auf die These und nicht auf Statements und Parteien.

**Comment by jnnkB** [comment]
Die Parteien die zur Auswahl stehen zu speichern ist ja sehr einfach, man kann aber nicht einfach die Partei speichern, von der das Statement angezeigt werden soll, weil man dann auch die Lösung bereits aus der URL lesen kann.

**Comment by jnnkB** [comment]
Aktuell ist es so, dass bei jeder neuen Frage, die Angezeigt wird, einfach der fragment identifier der URI auf etwas wie WOM-27-14:Die PARTEI,NPD,PIRATEN,SPD gesetzt wird.

**Comment by jnnkB** [comment]
implemented in #23
