### ISSUE TITLE
Filters are inacessible to screenreaders

### ISSUE THREAD

**Issue by nkreer** [Jugendhackt/parteiduell-frontend#18]
The filters using ```U+2588``` (█) are inaccessible to screenreader users in a way that they are either not read out at all and grammar is broken, or they are read out as "Full Block Full Block ...". Consider moving that functionality to the client, where the user can have control over how things are displayed and the censored content can be displayed differently.

**Comment by redsolver** [comment]
Ah, wie praktisch.

**Comment by jnnkB** [comment]
@nkreer The only solution I could come up with is using

```html
<span aria-label="Partei" "=""><span aria-hidden="true">█████</span></span>
```
instead of █████.

Would this improve the experience for you?

**Comment by nkreer** [comment]
Maybe use "Wir" instead of "Partei", as they are most often referencing themselves. (But please check against your data! If you have cases in which one party mentions another, "Partei" seems like a fine choice to me.

However, this is not a very elegant solution as it requires screenreader users to navigate through multiple elements when reading the thesis, instead of being able to quickly read it all at once.

**Comment by jnnkB** [comment]
I noticed the problem you described but I didn‘t found an alternative to set text that is just read by screenreaders. 
Does anyone have a better idea?

**Comment by jnnkB** [comment]
And „Wir“ seems to be a better alternative to „Partei“.

**Comment by jnnkB** [comment]
I think I found a better solution for this. It's already pushed.
