### ISSUE TITLE
Create Sitemap.xml

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#19]

**Comment by PerhapsSomeone** [comment]
Um eine Sitemap zu erstellen müsste ich die Domain wissen auf der das Projekt gehostet wird.
Sitemaps erfordern URLs in voller Länge.

Ich habe eine Procfile gesehen, also Heroku?

**Comment by gruselhaus** [comment]
www.parteiduell.de

**Comment by PerhapsSomeone** [comment]
#25
