### ISSUE TITLE
Elements with ARIA roles must use a valid, non-abstract ARIA role

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#21]
<img width="784" alt="Bildschirmfoto 2019-10-24 um 22 31 01" src="https://user-images.githubusercontent.com/33380107/67522992-0cbd8480-f6ae-11e9-9970-645ab2b0e203.png">

https://github.com/Jugendhackt/parteiduell-frontend/blob/d3ca531531fd4275b26846ffd95e95d02dee7de4/src/Main.js#L201

**Comment by jnnkB** [comment]
Davor ist eigentlich ein ignore comment, weil ich nicht weiß wie ich da beheben soll. Jetzt verstehe ich nicht warum das dann überhaupt angezeigt wird.

**Comment by jnnkB** [comment]
Achso das liegt an deinem Code formatter
