### ISSUE TITLE
Wrong Icon iOS Homescreen 

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#29]
![IMG_1340](https://user-images.githubusercontent.com/33380107/65956122-f115e400-e449-11e9-9058-222d63c987f0.PNG)

**Comment by jnnkB** [comment]
Bei mir gehts …

**Comment by redsolver** [comment]
`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">` in der `index.html` sollte das eigentlich verhindern.

**Comment by redsolver** [comment]
Vllt. mit Safari mal neu hinzufügen

**Comment by jnnkB** [comment]
vllt weil du nen iphone x oder neuer hast?
