### ISSUE TITLE
Neuer Startbildschirm?

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#3]
<img width="1792" alt="Bildschirmfoto 2019-09-28 um 22 12 57" src="https://user-images.githubusercontent.com/33380107/65821980-2a2d3900-e23d-11e9-8852-8d9f61547082.png">

@lmaertens Ja oder Nein?

**Comment by lmaertens** [comment]
nein. das ist kein bug, das ist ein feature.
