### ISSUE TITLE
iOS doesn't update the webapp if added to homescreen

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-frontend#30]
introduced in #22

**Comment by redsolver** [comment]
Aber #22 hat doch nur das Preloading hinzugefügt, oder?

**Comment by jnnkB** [comment]
sorry #27

**Comment by redsolver** [comment]
Wie bereits erwähnt:
Ich konnte das Verhalten unter Android nicht reproduzieren, also kann ich leider auch nicht herausfinden woran es liegt. Eigentlich sollte die Seite erst gecacht werden, wenn ein Service Worker installiert wird und dieser das festlegt. Der Browser darf eine Webapp erst als PWA anzeigen, wenn ein Service Worker da ist. Ansonsten gibts nur das klassische "Link zur Seite auf dem Homebildschirm". Da passiert dann aber auch nix weiteres.

Gehört zu #15

**Comment by jnnkB** [comment]
@gruselhaus Bleibt es bei dir auch bei einer alten Version?

**Comment by gruselhaus** [comment]
> @gruselhaus Bleibt es bei dir auch bei einer alten Version?

Jup.

**Comment by jnnkB** [comment]
Sollten wir dann das "site.webmanifest" erstmal entfernen?
