### ISSUE TITLE
Contributors List

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#37]
@all-contributors please add @gruselhaus for code

**Comment by gruselhaus** [comment]
@all-contributors please add @gruselhaus for code

**Comment by gruselhaus** [comment]
@all-contributors please add @gruselhaus for maintenance and infra

**Comment by gruselhaus** [comment]
@redsolver, @jnnkB, @lmaertens, @Max20013108 Wollt ihr euch auch ergänzen?

**Comment by redsolver** [comment]
@all-contributors please add @redsolver for code

**Comment by jnnkB** [comment]
@all-contributors please add @jnnkb for code and design

**Comment by gruselhaus** [comment]
@all-contributors please add @jnnkB for code and design

**Comment by Smaxs2001** [comment]
@all-contributors please add Max20013108

**Comment by gruselhaus** [comment]
@all-contributors please add @Max20013108 for code and documentation
