### ISSUE TITLE
Confetti cuts off on mobile view

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#44]
![IMG_D7783E4E3EC1-1](https://user-images.githubusercontent.com/33380107/65963240-a3ee3e00-e45a-11e9-93d6-cf73967ee2c2.jpeg)

**Comment by livgm** [comment]
Das haben wir bei Jugend hackt schon gefühlt Stunden versucht zu fixen, Problem ist, dass in dem Moment, in dem das Konfetti anfängt, berechnet wird, wie weit runter es gehen muss (1 Screenlänge) und wenn man dann den Bildschirm verschiebt, ändert sich das natürlich. Wenn man einfach einige Pixel dazu rechnet, wird der Screen von Anfang an lang, also geht das auch nicht. Nur so als kleiner Hinweis

**Comment by redsolver** [comment]
Wie wärs mit einem Overlay, welches nicht mitscrollt für das Konfetti?

**Comment by jnnkB** [comment]
Sollte jetzt behoben sein. (8f30adb)

**Comment by gruselhaus** [comment]
> Sollte jetzt behoben sein. ([8f30adb](https://github.com/Jugendhackt/parteiduell-frontend/commit/8f30adbe0938fa3d8fb91f0cd5b88abce5dedb1d))

Jup, schaut gut aus 👍🏻
