### ISSUE TITLE
Show wich version is deployed

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-frontend#47]
@gruselhaus Could you display the version running on parteiduell.de somewhere?

**Comment by gruselhaus** [comment]
@jnnkB Was meinst du mit Version? Wir versionieren ja im Moment nicht wirklich. Eventuell der aktuellste Commit?

**Comment by jnnkB** [comment]
Das meinte ich

**Comment by gruselhaus** [comment]
Bin dran.

**Comment by jnnkB** [comment]
Wo findet man das jetzt?

**Comment by gruselhaus** [comment]
Das ganze ist trickiger als erwartet. Im Heroku Container steht mir leider nicht git zur Verfügung, dass ich den letzten Commit auslesen könnte.

**Comment by jnnkB** [comment]
Man kann den commit in `./.git/refs/heads/master` sehen. Ist die nicht gehashte Variante: `7f729012da52f3d902ee290a70eb5ac4c4aa5c76`

**Comment by gruselhaus** [comment]
Das Problem ist, dass das .git Verzeichnis im Container nicht Verfügbar ist.

Ich habe mal einen `ls-la` auf dem Server durchgeführt.

<img width="574" alt="Bildschirmfoto 2019-10-01 um 22 30 30" src="https://user-images.githubusercontent.com/33380107/65998305-57772280-e49b-11e9-97a9-4f4a8bfea5d6.png">

Eventuell kann ich mir den aktuellsten Commit über die GitHub API ziehen.

**Comment by gruselhaus** [comment]
@jnnkB https://www.parteiduell.de/version

**Comment by jnnkB** [comment]
Danke!
