### ISSUE TITLE
Quotes that aren't quotes

### ISSUE THREAD

**Issue by lmaertens** [Jugendhackt/parteiduell-frontend#48]
Wenn die Partei kein Statement abgegeben hat, dann kommen trotzdem Anführungszeichen, obwohl das ja eigentlich kein Zitat ist. Ich glaube, dass das Backend die Info sogar mitschickt.

**Comment by redsolver** [comment]
Durch https://github.com/Jugendhackt/parteiduell-backend/commit/282b9bbb28d2b7ccd9e294e8fcbb8005a9ea5ef2 sollten keine leeren Antworten mehr existieren.

**Comment by jnnkB** [comment]
Dann können wir das Issue schließen?
