### ISSUE TITLE
Access site without www

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-frontend#52]
**Describe the bug**

If you acces the site under [https://parteiduell.de](https://parteiduell.de) you get an CERT error:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/29376715/66065141-10466b80-e547-11e9-9e76-b681cbc596c4.png">

**Comment by gruselhaus** [comment]
Sieht leider im Moment nicht gut aus. GoDaddy erlaubt es nicht für die Root Domain ein CNAME zu setzten. Also leite ich im Moment Parteiduell.de auf www.parteiduell.de weiter. Für www.parteiduell.de lässt sich ein CNAME setzen. Die GoDaddy Weiterleitung unterstützt im Moment leider kein HTTPS.

@jnnkB kannst du mal https://gruselhaus.com aufrufen und schauen, ob der gleiche Fehler auftritt. Falls nicht, ziehe ich das Frontend von Heroku zu Netlify um.

**Comment by jnnkB** [comment]
Ja da ist es das gleiche

**Comment by redsolver** [comment]
Wie wär's, wenn wir die www Subdomain einfach weglassen?

**Comment by redsolver** [comment]
Achso, Heroku braucht einen CNAME record. Dann geht das natürlich nicht... Aber kann man nicht einfach einen A record setzen?

**Comment by gruselhaus** [comment]
https://devcenter.heroku.com/articles/apex-domains

**Comment by jnnkB** [comment]
> However, applications requiring SSL encryption should use the ALIAS/ANAME configuration on the root domain. Subdomain redirection will cause a browser error when the root domain is requested over SSL (i.e. https://example.com).

**Comment by gruselhaus** [comment]
Möglicherweise wird Parteiduell.de für ein paar Minuten offline sein. Ich versuche das DNS Management nach AWS umzuziehen.

**Comment by gruselhaus** [comment]
@jnnkB gute Nachrichten: die Websites sollten in spätestens 30min wieder online sein. Ich habe das Frontend jetzt in ein Droplet bei DigitalOccean verschoben und habe jetzt volle Kontrolle über den Server (hatte ich bei Heroku nicht). Der einzige Nachteil ist, dass uns jetzt der auto-deploy fehlt. Diesen werde ich über einen Cronjob nachziehen. Nicht wundern: www.parteiduell.de braucht noch ein SSL-Zertifikat.

**Comment by jnnkB** [comment]
Klingt gut!

**Comment by gruselhaus** [comment]
@jnnkB Checkst du gerade mal bei dir, ob es wieder funzt?

**Comment by jnnkB** [comment]
mit https nichts/timeout
ohne internal server error

**Comment by gruselhaus** [comment]
Liegt wahrscheinlich an deinem DNS. 

Kannst du bitte mal `nslookup Parteiduell.de` ausführen?

**Comment by gruselhaus** [comment]
und `dig Parteiduell.de`

**Comment by gruselhaus** [comment]
@jnnkB Wie sieht es jetzt bei dir aus? Kann dieses Issue geschlossen werden?

**Comment by jnnkB** [comment]
Handy geht, Computer nicht

**Comment by gruselhaus** [comment]
Ok, ich glaube, es liegt an deinem Cache. Ich habe es jetzt aus mehreren Netzwerken und Maschinen getestet und es lief überall.

**Comment by gruselhaus** [comment]
Ich schließe dieses Issue erstmal.
