### ISSUE TITLE
Misplaced Button

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#61]
Können wir den Button für die Einstellung ein bisschen prominenter Platzieren? Ich finde, dass er aktuell dort oben rechts sehr abgeschnitten steht.

<img width="1792" alt="Bildschirmfoto 2019-10-03 um 23 41 59" src="https://user-images.githubusercontent.com/33380107/66166421-93df8580-e637-11e9-8075-d08a08a659a3.png">

**Comment by jnnkB** [comment]
Wenn du eine gute Idee hast gerne.

**Comment by gruselhaus** [comment]
Vllt. irgendwie so?

![1](https://user-images.githubusercontent.com/33380107/66194446-c2d81480-e694-11e9-8d6e-9f2eb85c864b.png)

**Comment by jnnkB** [comment]
Und dann auf dem Handy?

**Comment by gruselhaus** [comment]
Ok, das ist ein Argument.
