### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#7]
Reminder ⏰

**Comment by redsolver** [comment]
[Darkmode.Js](https://darkmodejs.learn.uno/) wäre eine Option, um den Dark Mode einfach hinzuzufügen.

**Comment by jnnkB** [comment]
Ich hätte jetzt gedacht, dass man einfach einen darkmode per Hand mittels CSS implementiert und, dass dann über die media query das richtige ausgewählt wird. So wie hier erklärt: https://css-tricks.com/dark-modes-with-css/

Ich das mal zu, testen ausprobiert, so würde es mit darkmode.js aussehen:
![image](https://user-images.githubusercontent.com/29376715/65836551-95d0de00-e2f1-11e9-9ca8-4aa7a6c70ca2.png)

Was haltet ihr für die bessere Option?

**Comment by gruselhaus** [comment]
Einige Logos müssten noch entsprechend angepasst werden. Ansonsten 👍🏻

**Comment by jnnkB** [comment]
Auch Schatten sehen noch nicht so gut aus.

**Comment by jnnkB** [comment]
Und was haltet ihr von dem Button. Ich empfinde ihn eher als störend und würde ihn daher weglassen.

**Comment by gruselhaus** [comment]
Bin da deiner Meinung.

**Comment by redsolver** [comment]
```▶️ 
Methods
If you don't want to show the widget and enable/disable Darkmode programatically you can use the method toggle(). You can also check if the darkmode is activated with the method isActivated(). See them in action in the following example.

const darkmode =  new Darkmode();
darkmode.toggle();
console.log(darkmode.isActivated()) // will return true```

https://darkmodejs.learn.uno/#%EF%B8%8F-methods

**Comment by gruselhaus** [comment]
@jnnkB Wie sieht's aus?

**Comment by PerhapsSomeone** [comment]
#212121 als Hintergrund wäre sehr viel besser. Ich finde den Kontrast so viel zu stark.

**Comment by redsolver** [comment]
Wie kann der Dark Mode aktiviert werden?

**Comment by jnnkB** [comment]
Ich mache das über eine media query: `@media (prefers-color-scheme: dark)`
Daher kann man das nur im Browser bzw. Betriebsystem einstellen

**Comment by jnnkB** [comment]
https://caniuse.com/#search=prefers-color-scheme
