### ISSUE TITLE
Confetti cuts off on mobile view

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-frontend#9]
![IMG_D7783E4E3EC1-1](https://user-images.githubusercontent.com/33380107/65963240-a3ee3e00-e45a-11e9-93d6-cf73967ee2c2.jpeg)

**Comment by livgm** [comment]
hmm, wenn jemand von euch weiß, wie man das am besten macht, dann ist das sicherlich eine gute idee
